# -----------------------------------------------------------
# Proyecto: Five Force Competence
# Descripción: Configuración del proyecto Flutter.
# Autor: Marcos Alejandro Collazos Marmolejo & Geraldine Perilla Valderrama
# Fecha: 2025-03-18
# -----------------------------------------------------------

# -----------------------------------------------------------
# Información básica del proyecto
# -----------------------------------------------------------
name: five_force_competence
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment: 
  sdk: ^3.7.0 
# -----------------------------------------------------------
# Dependencias del proyecto
# -----------------------------------------------------------
dependencies:

  # Configuración del Framework Flutter
  flutter:
    sdk: flutter

  # Integración con Bloc
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  # Integración con Flame Engine
  flame: ^1.27.0

  # Integración con Firebase
  firebase_core: ^3.12.1         # Configuración principal de Firebase
  firebase_auth: ^5.5.1          # Manejo de autenticación de usuarios en Firebase
  google_sign_in: ^6.3.0         # Integración con autenticación de Google
  firebase_database: ^11.3.4     # Manejo de Firebase Realtime Database
  
  # Módulos auxiliares
  http: ^1.3.0                    # Cliente HTTP para realizar peticiones REST
  connectivity_plus: ^6.1.3       # Manejo de conectividad (WiFi, datos móviles, etc.)
  flutter_secure_storage: ^9.2.4  # Almacenamiento seguro
  shared_preferences: ^2.5.2      # Almacenamiento de datos persitentes
  equatable: ^2.0.7


  # Hermientas de pruebas unitarias
  
# -----------------------------------------------------------
# Dependencias para desarrollo y pruebas
# -----------------------------------------------------------
dev_dependencies:
  flutter_launcher_icons : "^0.14.3"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


# Hermientas de pruebas unitarias


# -----------------------------------------------------------
# Configuración general de Flutter
# -----------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/Icon/LOGO.png
    - assets/Icon/FONDO PRINCIPAL.jpg
    - assets/Icon/FONDO GENERAL.png
    - assets/Icon/FONDO FINAL.jpg

    - assets/images/

# -----------------------------------------------------------
# Configuración de los íconos de la aplicación
# -----------------------------------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Icon/LOGO.png"
  web:
    generate: true
    image_path: "assets/Icon/LOGO.png"
    background_color: "#ffffff" # Color de fondo del icono (cambia según necesites)
    theme_color: "#000000" # Color de tema para la web
  windows:
    generate: true
    image_path: "assets/Icon/LOGO.png"
    icon_size: 48 # min: 48, max: 256, por defecto 48
  macos:
    generate: true
    image_path: "assets/Icon/LOGO.png"
